# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection 01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcIvYmyynCI79nUpcOJau_UsOxVxs9Or
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

# Upload your CSV
from google.colab import files

uploaded = files.upload()

# Load the CSV
df = pd.read_csv("creditcard.csv")

print("Dataset loaded successfully!")

df.head()

# Find the size of the dataset
print("Rows and Columns:", df.shape)

# See all column names
print(df.columns)

# Understand the dataset information
df.info()

# Statistical information
df.describe()

# Check missing values
print(df.isnull().sum())

print("Total missing values:", df.isnull().sum().sum())

# Check duplicate transactions
print("Duplicate rows:", df.duplicated().sum())

# Check fraud and legitimate transactions
print(df["Class"].value_counts())

# Calculate percentages
class_percentage = df["Class"].value_counts(normalize=True) * 100

print(class_percentage)

# Make a fraud distribution graph
plt.figure(figsize=(6, 4))

sns.countplot(x="Class", data=df)

plt.title("Legitimate vs Fraudulent Transactions")
plt.xlabel("Class")
plt.ylabel("Number of Transactions")

plt.show()

# Understand transaction amount
plt.figure(figsize=(8, 5))

sns.histplot(df["Amount"], bins=50)

plt.title("Transaction Amount Distribution")
plt.xlabel("Transaction Amount")
plt.ylabel("Frequency")

plt.show()

# Compare transaction amount by class
plt.figure(figsize=(8, 5))

sns.boxplot(x="Class", y="Amount", data=df)

plt.title("Transaction Amount: Legitimate vs Fraud")
plt.xlabel("Class")
plt.ylabel("Amount")

plt.show()

# Understand Time
plt.figure(figsize=(10, 5))

sns.histplot(df["Time"], bins=50)

plt.title("Transaction Time Distribution")
plt.xlabel("Time")
plt.ylabel("Number of Transactions")

plt.show()

# Correlation analysis
plt.figure(figsize=(14, 10))

sns.heatmap(
    df.corr(),
    cmap="coolwarm",
    linewidths=0.1
)

plt.title("Correlation Heatmap")

plt.show()

# Prepare X and y
X = df.drop("Class", axis=1)
y = df["Class"]

print("X shape:", X.shape)
print("y shape:", y.shape)

# Split training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

# Scale the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[["Time", "Amount"]] = scaler.fit_transform(
    X_train[["Time", "Amount"]]
)

X_test_scaled[["Time", "Amount"]] = scaler.transform(
    X_test[["Time", "Amount"]]
)

# Now train the ML model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(X_train_scaled, y_train)

print("Model training completed!")

# Make predictions
y_pred = model.predict(X_test_scaled)

print(y_pred[:20])

# Evaluate the model
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

# Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()